export enum QueryKeys {
  PRODUCTS = 'products',
  CATEGORIES = 'categories',
  STOCK_HISTORY = 'stock-history',
  SHIFT = 'shift',
  SHIFTS = 'shifts',
  SALES = 'sales',
  FISCAL = 'fiscal',
  POSITIONS = 'positions',
  UNITS = 'units',
  ME = 'me',
  USERS = 'users',
  CHAT = 'chat',
  CHAT_HISTORY = 'chat-history',
  CHAT_MEMBERS = 'chat-members',
  CHAT_UNREAD = 'chat-unread',
  CHAT_COLLEAGUES = 'chat-colleagues',
  CHAT_ONLINE = 'chat-online',
  CHAT_SEARCH = 'chat-search',
}
