export enum QueryKeys {
  PASSES = 'passes',
  POSITIONS = 'positions',
  UNITS = 'units',
  ME = 'me',
  USERS = 'users',
  HOSTS = 'hosts',
  REPORT_SUMMARY = 'report-summary',
  REPORT_PASSES = 'report-passes',
  CHAT = 'chat',
  CHAT_HISTORY = 'chat-history',
  CHAT_MEMBERS = 'chat-members',
  CHAT_UNREAD = 'chat-unread',
  CHAT_ONLINE = 'chat-online',
  CHAT_SEARCH = 'chat-search',
}
